
package org.tektutor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://tektutor.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param x
     * @param y
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://tektutor.org")
    @RequestWrapper(localName = "add", targetNamespace = "http://tektutor.org", className = "org.tektutor.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://tektutor.org", className = "org.tektutor.AddResponse")
    public double add(
        @WebParam(name = "x", targetNamespace = "http://tektutor.org")
        double x,
        @WebParam(name = "y", targetNamespace = "http://tektutor.org")
        double y);

}
